DROP SCHEMA  IF EXISTS bancobbdd;
CREATE SCHEMA `bancobbdd` ;
CREATE TABLE `bancobbdd`.`cuentas` (
  `NUM_CUENTA` INT NOT NULL AUTO_INCREMENT,
  `ALIAS` VARCHAR(100) NOT NULL,
  `SALDO` FLOAT NOT NULL,
  PRIMARY KEY (`NUM_CUENTA`));
CREATE TABLE `bancobbdd`.`movimientos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` TEXT NOT NULL,
  `FECHA` DATE NOT NULL,
  `IMPORTE` FLOAT NOT NULL,
  `NUM_CUENTA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `NUM_CUENTA_idx` (`NUM_CUENTA` ASC) VISIBLE,
  CONSTRAINT `NUM_CUENTA`
    FOREIGN KEY (`NUM_CUENTA`)
    REFERENCES `bancobbdd`.`cuentas` (`NUM_CUENTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    CREATE TABLE `bancobbdd`.`tipos_movimiento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
ALTER TABLE `bancobbdd`.`movimientos` 
ADD COLUMN `ID_TIPO` INT NOT NULL AFTER `NUM_CUENTA`,
ADD INDEX `ID_idx` (`ID_TIPO` ASC) VISIBLE;
ALTER TABLE `bancobbdd`.`movimientos` 
ADD CONSTRAINT `ID`
  FOREIGN KEY (`ID_TIPO`)
  REFERENCES `bancobbdd`.`tipos_movimiento` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  CREATE TABLE `bancobbdd`.`clientes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USUARIO` VARCHAR(100) NOT NULL,
  `PASS` VARCHAR(10) NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`));
  ALTER TABLE `bancobbdd`.`clientes` 
ADD UNIQUE INDEX `USUARIO_UNIQUE` (`USUARIO` ASC) VISIBLE;
ALTER TABLE `bancobbdd`.`cuentas` 
ADD COLUMN `ID_CLIENTES` INT NOT NULL AFTER `SALDO`,
ADD INDEX `ID_CLIENTE_idx` (`ID_CLIENTES` ASC) VISIBLE;
;
ALTER TABLE `bancobbdd`.`cuentas` 
ADD CONSTRAINT `ID_CLIENTE`
  FOREIGN KEY (`ID_CLIENTES`)
  REFERENCES `bancobbdd`.`clientes` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  CREATE TABLE `bancobbdd`.`prestamos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` TEXT NULL,
  `FECHA` DATE NOT NULL,
  `IMPORTE` FLOAT NOT NULL,
  `PLAZOS` INT NOT NULL,
  `ID_CUENTA` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `NUM_CUENTA_idx` (`ID_CUENTA` ASC) VISIBLE,
  CONSTRAINT `ID_CUENTA`
    FOREIGN KEY (`ID_CUENTA`)
    REFERENCES `bancobbdd`.`cuentas` (`NUM_CUENTA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
CREATE TABLE `bancobbdd`.`amortizaciones` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NOT NULL,
  `IMPORTE` FLOAT NOT NULL,
  `ID_PRESTAMO` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_PRESTAMO_idx` (`ID_PRESTAMO` ASC) VISIBLE,
  CONSTRAINT `ID_PRESTAMO`
    FOREIGN KEY (`ID_PRESTAMO`)
    REFERENCES `bancobbdd`.`prestamos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    ALTER TABLE `bancobbdd`.`prestamos` 
DROP FOREIGN KEY `ID_CUENTA`;
ALTER TABLE `bancobbdd`.`prestamos` 
CHANGE COLUMN `ID_CUENTA` `NUM_CUENTA` INT(11) NOT NULL ;
ALTER TABLE `bancobbdd`.`prestamos` 
ADD CONSTRAINT `ID_CUENTA`
  FOREIGN KEY (`NUM_CUENTA`)
  REFERENCES `bancobbdd`.`cuentas` (`NUM_CUENTA`);
